version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: enigma-coop-2
    depends_on:
      - db
    environment:
      - DB_HOST=${DB_HOST}
        - DB_PORT=${DB_PORT}
        - DB_NAME=${DB_NAME}
        - DB_USERNAME=${DB_USERNAME}
        - DB_PASSWORD=${DB_PASSWORD}
        - API_PORT=${API_PORT}
        - JWT_APP_NAME=${JWT_APP_NAME}
        - JWT_EXPIRATION=${JWT_EXPIRATION}
        - JWT_SECRET=${JWT_SECRET}
        - USERNAME_ADMIN=${USERNAME_ADMIN}
        - PASSWORD_ADMIN=${PASSWORD_ADMIN}
        - MIDTRANS_API_KEY=${MIDTRANS_API_KEY}
        - MIDTRANS_SNAP_URL=${MIDTRANS_SNAP_URL}
        - IMAGE_PATH=${IMAGE_PATH}
    ports:
      - "${API_PORT}:${API_PORT}"
    networks:
      - todo-network
  db:
    image: postgres:alpine3.17
    container_name: postgres-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=P@ssw0rd123
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      -  coop_network
volumes:
  db-data:
networks:
  coop_network: